### ISSUE TITLE
无法完全卸载

### ISSUE THREAD

**Issue by unbadfish** [AShujiao/vscode-nest#1]
点击卸载后重启vscode，组件依然存在，vscode提示安装可能损坏。
然后把adminstor\/.vscode和安装目录全删除了重新安装了一遍，成功卸载
~~然后花了十分钟重新安装别的附加组件~~

**Comment by AShujiao** [comment]
你应该是少了一个步骤，当前是利用卸载钩子清除的js。步骤为卸载后重启执行卸载钩子事件，然后再关闭vscode再次重启才会完全卸载。
